from src.components.DB.db import connect_to_postgres
from pandas import DataFrame

engine = connect_to_postgres()

labels = {'DR_6.7': 'Data release 6.7', 'DR_6.6': 'Data release 6.6', 'DR_6.5': 'Data release 6.5', 'DR_6.4': 'Data release 6.4', 'DR_6.3': 'Data release 6.3', 'DR_6.2': 'Data release 6.2', 'DR_6.1': 'Data release 6.1', 'DR_6.0': 'Data release 6.0',
          'DR_5.3': 'Data release 5.3', 'DR_5.2': 'Data release 5.2', 'DR_5.1': 'Data release 5.1',
          'DR_4.0': 'Data release 4.0',
          'DR_3.1': 'Data release 3.1', 'DR_3.0': 'Data release 3.0',
          'DR_2.1': 'Data release 2.1', 'DR_2.0': 'Data release 2.0',
          'DR_1.0': 'Data release 1.0'}

reactive_categories = {'Country': 'country', 'Providers': 'provider', 'Model Type': 'model_type',
                 'Publications': 'publications', 'Age': 'age_in_years_at_collection',
                 'Cancer System': 'diagnosis', 'Tumour Type': 'tumour_type',
                 'Primary Site': 'primary_site', 'Gender': 'sex', 'Ethnicity': 'ethnicity'}

summary_columns = ['tag', 'links', 'date', "model_type_pdx", "model_type_cell_line", "model_type_organoid", "model_type_other", "model_type_total", "sample_type_xenograft", "sample_type_cell", "sample_type_patient", "sample_type_total", "molecular_data_biomarker", "molecular_data_cna", "molecular_data_expression", "molecular_data_immunemarker", "molecular_data_mut", "molecular_data_points_total", "drug_data_points", "treatment_data_points", "image_data_points"]

summary = DataFrame(columns=summary_columns)

padding = "0.5%"
margin_left = '0.1%'
margin_bottom = "0.1%"
border = '0.5px solid #000'
bgcolor = '#f4f4f4'
br = '10px'
component_style_1 = {'border': border, 'background-color': bgcolor, 'padding': padding, 'border-radius': br,
                     'width': '31.4%', 'float': 'left', 'margin-bottom': margin_bottom, 'margin-left': margin_left}
component_style_2 = {'border': border, 'background-color': bgcolor, 'padding': padding, 'border-radius': br,
                     'width': '64.1%', 'float': 'left', 'margin-bottom': margin_bottom, 'margin-left': margin_left}
component_style_3 = {'border': border, 'background-color': bgcolor, 'padding': padding, 'border-radius': br,
                     'width': '33.2%', 'float': 'right', 'margin-bottom': margin_bottom, 'margin-left': margin_left}
component_style_4 = {'border': border, 'background-color': bgcolor, 'padding': padding, 'border-radius': br,
                     'width': '32%', 'float': 'left', 'margin-bottom': margin_bottom, 'margin-left': margin_left}
component_style_5 = {'border': border, 'background-color': bgcolor, 'padding': padding, 'border-radius': br,
                     'width': '99%', 'float': 'left', 'margin-bottom': margin_bottom, 'margin-left': margin_left}


primary_site_mapping = {
    "Central Nervous System": [
        "4Th Ventricle", "Brain", "Brain Stem", "Cerebellum", "Cerebrum",
        "Frontal Cortex", "Frontal Lobe", "Infratemporal Fossa", "Occipital Mass",
        "Parietal Lobe", "Pineal", "Posterior Fossa", "Temporal Cortex",
        "Ventricular Mass", "Central Nervous System", "Neurologic",
        "Pontine Meninges", "Right Parietal Lobe", "Right Sylvian Fissure", "Thalamus"
    ],
    "Head and Neck": [
        "Base Of Tongue", "Buccal Mucosa", "Eye", "Face", "Floor Of Mouth",
        "Glottis", "Hard Palate", "Head", "Jaw", "Larynx", "Mouth", "Nasal Cavity",
        "Neck", "Oropharynx", "Oral Cavity", "Orbit", "Pharynx", "Salivary Gland",
        "Scalp", "Soft Tissue", "Supraglottis", "Tonsil", "Tongue", "Head And Neck",
        "Head Face Or Neck", "Neck Mass", "Left Occipital Mass", "Right Neck Mass",
        "Laryngeal", "Post-Cricoid", "Shoulder", "Supra-Orbital Area",
        "Paranasal", "Parapharyngeal", "Os Frontalis"
    ],
    "Thorax": [
        "Breast", "Breast Cancer (Her2-Enriched)", "Breast Cancer (Triple Negative)",
        "Chest", "Chest Mass", "Chest Wall", "Esophagus", "Lung",
        "Lung Recurrence (What Does This Mean)", "Lung Recurrence (Same)", "Mediastinum",
        "Pleura", "Respiratory/Thoracic", "Thoracic", "Thorax", "Bronchus And Lung",
        "Melanoma", "Small Cell Lung Cancer", "Pleural Cavity", "Posterior Mediastinum"
    ],
    "Abdomen and Pelvis": [
        "Abdomen", "Abdominal Mass", "Abdominal Wall", "Abdominalpelvic",
        "Adrenal", "Adrenal Gland", "Adrenal Mass", "Adrenal Resection",
        "Ampulla Of Vater", "Appendix", "Biliary Tract", "Bladder", "Bladder Cancer",
        "Bowel", "Caecum", "Cecum", "Colon", "Colon Cancer (Asian)",
        "Colon Cancer (Caucasian, Europe)", "Colorectal", "Duodenum", "Gallbladder",
        "Gastric", "Gastric Antrum", "Gastric Body Mucosa", "Gastric Cancer (Caucasian)",
        "Gastric Cardia", "Gastric Fundus", "Gastro Oesophageal Junction",
        "Gastroesophageal Junction", "Genitourinary", "Genitourinary Tract",
        "Hepatic Flexure", "Hepatic Flexure Of Colon", "Ileocecal Valve", "Kidney",
        "Large Intestine", "Left Colon", "Left Kidney", "Liver", "Liver And Intrahepatic Duct",
        "Liver Cancer (Caucasian, Cholangiocarcinoma)", "Liver/Biliary Ducts",
        "Oesophagus", "Pancreas", "Pancreas Head", "Pancreatic Cancer (Caucasian)",
        "Peritoneal Mass", "Rectosigmoid Colon", "Rectosigmoid Junction", "Rectum",
        "Sigmoid Colon", "Sigmoid Flexure", "Small Intestine", "Splenic Flexure Of Colon",
        "Stomach", "Transverse Colon", "Endocrine And Neuroendocrine",
        "Extrahepatic Bile Duct", "Intrahepatic Bile Duct", "Distal Pancreas",
        "Digestive/Gastrointestinal", "Gynecologic", "Omentum", "Pelvis",
        "Perineum", "Aortocaval", "Retroperitoneal Mass", "Retroperitoneum",
        "Retroperitoneum ", "Paraspinal Mass", "Paraspinal Mass Resection",
        "Paracaval Lymph Node", "Periorbital", "Peritracheal"
    ],
    "Lymphatic and Hematologic": [
        "Lymph Node", "Lymph Nodes", "Lymphoma", "Lymphoma (Dlbcl)",
        "Haematopoietic And Lymphoid", "Hematologic/Blood", "Leukemia",
        "Leukemia (Aml)", "Peripheral Blood", "Leukapheresis", "Lower Alveolus And Gingiva",
        "Renal Cancer (Caucasian)"
    ],
    "Musculoskeletal": [
        "Bone", "Bone Marrow", "Femur", "Humerus", "Muscle", "Musculoskeletal",
        "Skeletal Muscle", "Soft Tissue", "Back", "Back Mass", "Back Soft Tissue",
        "Distal Femur", "Femur ", "Leg", "Right Proximal Tibia", "Right Proximal Ulna",
        "Calf", "Arm", "Axilla", "Shoulder", "Inferior Leg", "Superior Leg", "Right Buttock",
        "Thigh", "Left Thigh", "Left Distal Femur", "Left Femur",
        "Left Proximal Humerus/Bone Marrow", "Left Proximal Tibia", "Tibia", "Rib",
        "8Th Rib", "Right Distal Femur", "Right Colon", "Right Kidney",
        "Femalelank Mass", "Right Proximal Tibia", "Spine", "Spleen"
    ],
    "Other": [
        "Not Collected", "Not Provided", "Unknown Cancer", "Unknown Primary", "Other", "Other (Specify)"
    ],
    "Reproductive": [
        "Ovary", "Prostate", "Prostate Cancer", "Prostate Gland", "Testes",
        "Testicle", "Testis", "Testis Cancer", "Uterus", "Vulva",
        "Peripheral Nervous System", "Placenta", "Gynecologic", "Upper Tract Urothelial Carcinoma (Utuc)"
    ]
}


#diagnosis_to_cancer = read_csv('assets/diagnosis_mappings.tsv', sep='\t')
#diagnosis_to_cancer = dict(zip(diagnosis_to_cancer['sample_diagnosis'], diagnosis_to_cancer['mappedTermLabel']))
#cancer_system = pd.read_json("https://www.cancermodels.org/api/model_metadata?select=histology,cancer_system").drop_duplicates()
#cancer_system['histology'] = cancer_system['histology'].str.title()
#cancer_system = None

diagnosis_to_cancer_system = {'glioblastoma nos': 'Nervous System Cancer',
 'glioblastoma gliosarcoma': 'Nervous System Cancer',
 'pancreatic cancer other': 'Digestive System Cancer',
 'stomach cancer adenocarcinoma (nos)': 'Digestive System Cancer',
 'osteosarcoma': 'Connective and Soft Tissue Cancer',
 'stomach cancer other': 'Digestive System Cancer',
 "ewing's sarcoma": 'Connective and Soft Tissue Cancer',
 'lung cancer carcinoma (nos)': 'Thoracic Cancer',
 'esophageal cancer esophagus adenocarcinoma (nos)': 'Digestive System Cancer',
 'pancreatic cancer adenocarcinoma ductal type': 'Digestive System Cancer',
 'rhabdomyosarcoma alveolar': 'Connective and Soft Tissue Cancer',
 'wilms tumor favorable': 'Urinary System Cancer',
 'rare cancers undifferentiated sarcoma': 'Connective and Soft Tissue Cancer',
 'rare cancers epithelioid sarcoma': 'Connective and Soft Tissue Cancer',
 'rare cancers spindle cell sarcoma': 'Connective and Soft Tissue Cancer',
 'melanoma': 'Nervous System Cancer',
 'lung cancer squamous cell carcinoma (nos)': 'Thoracic Cancer',
 'colorectal cancer adenocarcinoma': 'Digestive System Cancer',
 'melanoma melanoma (nos)': 'Skin Cancer',
 'pancreatic cancer adenocarcinoma (nos)': 'Digestive System Cancer',
 'pancreatic cancer moderately differentiated adenocarcinoma': 'Digestive System Cancer',
 'glioblastoma': 'Nervous System Cancer',
 'wilms tumor unfavorable': 'Urinary System Cancer',
 'rare cancers papillary carcinoma, nos': 'Endocrine Cancer',
 'stomach cancer undifferentiated carcinoma': 'Digestive System Cancer',
 'rare cancers abdominal fibromatosis': 'Connective and Soft Tissue Cancer',
 'lung cancer adenocarcinoma (nos)': 'Thoracic Cancer',
 'ovarian cancer high grade serous carcinoma': 'Reproductive System Cancer',
 'kidney cancer renal medullary carcinoma': 'Urinary System Cancer',
 'rare cancers prolymphocytic leukemia, t-cell type': 'Hematopoietic and Lymphoid System Cancer',
 'rare cancers papillary adenocarcinoma': 'Endocrine Cancer',
 'rare cancers sezary syndrome': 'Hematopoietic and Lymphoid System Cancer',
 'rare cancers non-hodgkin lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'rare cancers leiomyosarcoma': 'Connective and Soft Tissue Cancer',
 'stomach cancer tubular (intestinal) adenocarcinoma': 'Digestive System Cancer',
 'neuroblastoma unfavorable': 'Nervous System Cancer',
 'uterine sarcoma leiomyosarcoma': 'Connective and Soft Tissue Cancer',
 'kidney cancer chromophobe renal cell carcinoma': 'Urinary System Cancer',
 'kidney cancer clear cell renal cell carcinoma': 'Urinary System Cancer',
 'medulloblastoma large cell/anaplastic medulloblastoma': 'Nervous System Cancer',
 'kidney cancer renal cell carcinoma': 'Urinary System Cancer',
 'rare cancers mature t-cell lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'stomach cancer signet ring cell carcinoma': 'Digestive System Cancer',
 'ovarian cancer carcinosarcoma (malignant mixed mullerian tumor)': 'Reproductive System Cancer',
 'rare cancers clear cell sarcoma': 'Connective and Soft Tissue Cancer',
 'rare cancers angioimmunoblastic t-cell lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'ovarian cancer endometrioid carcinoma': 'Reproductive System Cancer',
 'breast cancer carcinoma': 'Breast Cancer',
 'lung cancer small cell carcinoma': 'Endocrine Cancer',
 'head and neck cancer: lip and oral cavity squamous cell carcinoma': 'Head and Neck Cancer',
 'head and neck cancer: lip and oral cavity squamous cell carcinoma, keratinizing': 'Head and Neck Cancer',
 'pancreatic cancer signet ring cell carcinoma': 'Digestive System Cancer',
 'b-cell precursor acute lymphoblastic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'mixed lineage lukemia acute lymphoblastic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'philadelphia chromosome positive acute lymphoblastic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 't-cell lymphoblastic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'philadelphia chromosome negative like acute lymphoblastic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'early t-cell precursor acute lymphoblastic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'ewing sarcoma': 'Connective and Soft Tissue Cancer',
 'neuroblastoma': 'Nervous System Cancer',
 'pancreatic carcinoma': 'Digestive System Cancer',
 'rectal adenocarcinoma': 'Digestive System Cancer',
 'pleural epithelioid mesothelioma': 'Thoracic Cancer',
 'b acute lymphoblastic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'astrocytoma': 'Nervous System Cancer',
 'hepatocellular carcinoma': 'Digestive System Cancer',
 'bladder carcinoma': 'Urinary System Cancer',
 'endometrial adenocarcinoma': 'Reproductive System Cancer',
 "burkitt's lymphoma": 'Hematopoietic and Lymphoid System Cancer',
 'small cell lung carcinoma': 'Endocrine Cancer',
 'colon adenocarcinoma': 'Digestive System Cancer',
 'plasma cell myeloma': 'Hematopoietic and Lymphoid System Cancer',
 'non-small cell lung carcinoma': 'Thoracic Cancer',
 'childhood t acute lymphoblastic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'papillary lung adenocarcinoma': 'Thoracic Cancer',
 'not provided': 'Digestive System Cancer',
 'chronic myelogenous leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'pancreatic adenocarcinoma': 'Digestive System Cancer',
 "hodgkin's lymphoma": 'Hematopoietic and Lymphoid System Cancer',
 'intrahepatic cholangiocarcinoma': 'Digestive System Cancer',
 'lung adenocarcinoma': 'Thoracic Cancer',
 'laryngeal squamous cell carcinoma': 'Head and Neck Cancer',
 'breast carcinoma': 'Breast Cancer',
 'embryonal rhabdomyosarcoma': 'Connective and Soft Tissue Cancer',
 'bronchiolo-alveolar lung carcinoma': 'Thoracic Cancer',
 'cervical small cell carcinoma': 'Endocrine Cancer',
 'lung carcinoid tumor': 'Endocrine Cancer',
 'esophageal adenocarcinoma': 'Digestive System Cancer',
 'childhood acute megakaryoblastic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'hairy cell leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'gastric adenocarcinoma': 'Digestive System Cancer',
 'renal cell carcinoma': 'Urinary System Cancer',
 'adult t acute lymphoblastic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'medulloblastoma': 'Nervous System Cancer',
 'squamous cell lung carcinoma': 'Thoracic Cancer',
 'lung mucoepidermoid carcinoma': 'Thoracic Cancer',
 'erythroleukemia': 'Hematopoietic and Lymphoid System Cancer',
 'non-cancerous': 'Hematopoietic and Lymphoid System Cancer',
 'anaplastic astrocytoma': 'Nervous System Cancer',
 'follicular lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'undifferentiated gallbladder carcinoma': 'Digestive System Cancer',
 'small cell sarcoma': 'Connective and Soft Tissue Cancer',
 'childhood b acute lymphoblastic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'adult acute myeloid leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'ductal breast carcinoma': 'Breast Cancer',
 'rhabdomyosarcoma': 'Breast Cancer',
 'invasive ductal carcinoma not otherwise specified': 'Breast Cancer',
 'tongue squamous cell carcinoma': 'Head and Neck Cancer',
 'diffuse large b-cell lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'thyroid gland anaplastic carcinoma squamous cell carcinoma pattern': 'Head and Neck Cancer',
 'ampulla of vater adenocarcinoma': 'Digestive System Cancer',
 'adrenal gland neuroblastoma': 'Nervous System Cancer',
 'mantle cell lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'gastric carcinoma': 'Digestive System Cancer',
 'chronic lymphocytic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'cutaneous melanoma': 'Skin Cancer',
 'high grade ovarian serous adenocarcinoma': 'Reproductive System Cancer',
 'amelanotic melanoma': 'Skin Cancer',
 'rectosigmoid adenocarcinoma': 'Digestive System Cancer',
 'ovarian serous adenocarcinoma': 'Reproductive System Cancer',
 'follicular thyroid carcinoma': 'Endocrine Cancer',
 'gliosarcoma': 'Nervous System Cancer',
 'hilar cholangiocarcinoma': 'Digestive System Cancer',
 'hypopharyngeal squamous cell carcinoma': 'Head and Neck Cancer',
 'hepatoblastoma': 'Digestive System Cancer',
 'oral cavity squamous cell carcinoma': 'Head and Neck Cancer',
 'pleural sarcomatoid mesothelioma': 'Thoracic Cancer',
 'malignant pleural mesothelioma': 'Thoracic Cancer',
 'esophageal squamous cell carcinoma': 'Digestive System Cancer',
 'pancreatic ductal adenocarcinoma': 'Digestive System Cancer',
 'prostate carcinoma': 'Reproductive System Cancer',
 'cholangiocarcinoma': 'Digestive System Cancer',
 'uterine corpus carcinosarcoma': 'Reproductive System Cancer',
 'gastric tubular adenocarcinoma': 'Digestive System Cancer',
 'papillary renal cell carcinoma': 'Urinary System Cancer',
 'head and neck squamous cell carcinoma': 'Head and Neck Cancer',
 'adenosquamous lung carcinoma': 'Thoracic Cancer',
 'breast adenocarcinoma': 'Breast Cancer',
 'clear cell renal cell carcinoma': 'Urinary System Cancer',
 'papillary thyroid carcinoma': 'Endocrine Cancer',
 'merkel cell carcinoma': 'Endocrine Cancer',
 'chondrosarcoma': 'Connective and Soft Tissue Cancer',
 'gastric small cell neuroendocrine carcinoma': 'Digestive System Cancer',
 'chronic eosinophilic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'testicular embryonal carcinoma': 'Reproductive System Cancer',
 'pyriform fossa squamous cell carcinoma': 'Head and Neck Cancer',
 'gallbladder carcinoma': 'Digestive System Cancer',
 'gestational choriocarcinoma': 'Reproductive System Cancer',
 'ovarian cystadenocarcinoma': 'Reproductive System Cancer',
 'adult b acute lymphoblastic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'skin squamous cell carcinoma': 'Skin Cancer',
 'large cell lung carcinoma': 'Thoracic Cancer',
 'ovarian granulosa cell tumor': 'Reproductive System Cancer',
 'undifferentiated pleomorphic sarcoma': 'Connective and Soft Tissue Cancer',
 'gastric adenosquamous carcinoma': 'Digestive System Cancer',
 'cervical squamous cell carcinoma': 'Reproductive System Cancer',
 "b-cell non-hodgkin's lymphoma": 'Hematopoietic and Lymphoid System Cancer',
 'giant cell lung carcinoma': 'Thoracic Cancer',
 'pancreatic adenosquamous carcinoma': 'Digestive System Cancer',
 'acute biphenotypic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'ovarian clear cell adenocarcinoma': 'Reproductive System Cancer',
 'pancreatic somatostatinoma': 'Digestive System Cancer',
 'ovarian leiomyosarcoma': 'Connective and Soft Tissue Cancer',
 'gastric choriocarcinoma': 'Digestive System Cancer',
 'cervical adenocarcinoma': 'Reproductive System Cancer',
 'gastric fundus carcinoma': 'Digestive System Cancer',
 'human papilloma virus-related cervical squamous cell carcinoma': 'Reproductive System Cancer',
 'uterine corpus leiomyosarcoma': 'Connective and Soft Tissue Cancer',
 'splenic marginal zone b-cell lymphoma with villous lymphocytes': 'Hematopoietic and Lymphoid System Cancer',
 'anaplastic large cell lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'precursor lymphoblastic lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'thyroid gland anaplastic carcinoma': 'Head and Neck Cancer',
 'gingival squamous cell carcinoma': 'Head and Neck Cancer',
 'epstein-barr virus-related burkitt s lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'acute promyelocytic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'barrett s adenocarcinoma': 'Digestive System Cancer',
 'ovarian carcinoma': 'Reproductive System Cancer',
 'acute myeloid leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'hereditary thyroid gland medullary carcinoma': 'Endocrine Cancer',
 'natural killer cell lymphoblastic leukemia or lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'lung carcinoma': 'Thoracic Cancer',
 'oral dysplasia': "Not provided",
 'vulvar melanoma': 'Reproductive System Cancer',
 'pleural biphasic mesothelioma': 'Thoracic Cancer',
 'parotid gland mucoepidermoid carcinoma': 'Head and Neck Cancer',
 'acute myelomonocytic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'alveolar rhabdomyosarcoma': 'Connective and Soft Tissue Cancer',
 'colon carcinoma': 'Digestive System Cancer',
 'ovarian adenocarcinoma': 'Reproductive System Cancer',
 'sacral chordoma': 'Connective and Soft Tissue Cancer',
 'mycosis fungoides and sezary syndrome': 'Hematopoietic and Lymphoid System Cancer',
 'adult acute monocytic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'signet ring cell gastric adenocarcinoma': 'Digestive System Cancer',
 'cutaneous t-cell lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'fibrosarcoma': 'Connective and Soft Tissue Cancer',
 'oligodendroglioma': 'Nervous System Cancer',
 'primary effusion lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'cecum adenocarcinoma': 'Nervous System Cancer',
 'uterine corpus sarcoma': 'Connective and Soft Tissue Cancer',
 'childhood acute differentiated monocytic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'hereditary spherocytosis': 'Not provided',
 'cervical carcinoma': 'Reproductive System Cancer',
 'duodenal adenocarcinoma': 'Digestive System Cancer',
 'adrenal cortex carcinoma': 'Endocrine Cancer',
 'salivary gland squamous cell carcinoma': 'Head and Neck Cancer',
 'pharyngeal squamous cell carcinoma': 'Head and Neck Cancer',
 'rhabdoid tumour of the kidney': 'Urinary System Cancer',
 'epithelioid cell type gastrointestinal stromal tumor': 'Connective and Soft Tissue Cancer',
 'squamous cell breast carcinoma acantholytic variant': 'Breast Cancer',
 'ovarian endometrioid adenocarcinoma': 'Reproductive System Cancer',
 'vulvar squamous cell carcinoma': 'Reproductive System Cancer',
 'bronchogenic carcinoma': 'Thoracic Cancer',
 'childhood acute myeloid leukemia with maturation': 'Hematopoietic and Lymphoid System Cancer',
 'renal pelvis urothelial carcinoma': 'Urinary System Cancer',
 'ovarian serous cystadenocarcinoma': 'Reproductive System Cancer',
 'b-cell prolymphocytic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'mediastinal thymic large b-cell cell lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'endometrial stromal sarcoma': 'Connective and Soft Tissue Cancer',
 'ovarian mixed germ cell tumor': 'Reproductive System Cancer',
 'vulvar leiomyosarcoma': 'Connective and Soft Tissue Cancer',
 'primitive neuroectodermal tumor': 'Nervous System Cancer',
 'epithelioid sarcoma': 'Connective and Soft Tissue Cancer',
 'glioma': 'Nervous System Cancer',
 'liposarcoma': 'Connective and Soft Tissue Cancer',
 'childhood precursor t lymphoblastic lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'vulvar carcinoma': 'Reproductive System Cancer',
 'synovial sarcoma': 'Connective and Soft Tissue Cancer',
 'undifferentiated sarcoma - not otherwise specified': 'Connective and Soft Tissue Cancer',
 'thyroid gland sarcoma': 'Connective and Soft Tissue Cancer',
 'retinoblastoma': 'Eye Cancer',
 'basaloid squamous cell carcinoma': 'Unclassified',
 'extrarenal rhabdoid tumor': 'Connective and Soft Tissue Cancer',
 'uveal melanoma': 'Eye Cancer',
 'renal pelvis carcinoma': 'Urinary System Cancer',
 'clivus chordoma': 'Connective and Soft Tissue Cancer',
 'centroblastic lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'malignant ovarian brenner tumor': 'Reproductive System Cancer',
 'rhabdoid tumor': 'Unclassified',
 'atypical teratoid/rhabdoid tumor': 'Nervous System Cancer',
 'hepatosplenic t-cell lymphoma': 'Digestive System Cancer',
 'monophasic synovial sarcoma': 'Connective and Soft Tissue Cancer',
 'meningioma': 'Nervous System Cancer',
 'melanotic neuroectodermal tumor': 'Unclassified',
 'colorectal adenocarcinoma': 'Digestive System Cancer',
 'ovarian small cell carcinoma, hypercalcemic type': 'Reproductive System Cancer',
 'myelodysplastic syndrome': 'Hematopoietic and Lymphoid System Cancer',
 'keratoacanthoma': 'Skin Cancer',
 'ovarian mucinous adenocarcinoma': 'Reproductive System Cancer',
 'mucinous gastric adenocarcinoma': 'Digestive System Cancer',
 'endometrial carcinoma': 'Reproductive System Cancer',
 'adult acute megakaryoblastic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'giant cell bone sarcoma': 'Connective and Soft Tissue Cancer',
 'colorectal carcinoma': 'Digestive System Cancer',
 'childhood acute myeloid leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'adenosquamous endometrial carcinoma': 'Reproductive System Cancer',
 'diffuse intrinsic pontine glioma': 'Nervous System Cancer',
 'mixed glioma': 'Nervous System Cancer',
 'dedifferentiated liposarcoma': 'Connective and Soft Tissue Cancer',
 'combined hepatocellular carcinoma and cholangiocarcinoma': 'Digestive System Cancer',
 'uterine carcinosarcoma': 'Reproductive System Cancer',
 'buccal mucosa squamous cell carcinoma': 'Head and Neck Cancer',
 'papillary serous cystadenocarcinoma': 'Unclassified',
 "t-cell non-hodgkin's lymphoma": 'Hematopoietic and Lymphoid System Cancer',
 'primary central chondrosarcoma': 'Connective and Soft Tissue Cancer',
 'testicular teratoma': 'Reproductive System Cancer',
 'invasive lobular breast carcinoma': 'Breast Cancer',
 'well differentiated liposarcoma': 'Connective and Soft Tissue Cancer',
 'malignant non-hodgkin lymphoma, cleaved cell': 'Hematopoietic and Lymphoid System Cancer',
 't-cell large granular lymphocyte leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'nasopharyngeal undifferentiated carcinoma': 'Head and Neck Cancer',
 'nasopharyngeal carcinoma': 'Head and Neck Cancer',
 'nasopharyngeal differentiated carcinoma': 'Head and Neck Cancer',
 "askin's tumor": 'Nervous System Cancer',
 'colon mucinous adenocarcinoma': 'Not provided',
 'biphasic mesothelioma': 'Thoracic Cancer',
 'epithelioid mesothelioma': 'Thoracic Cancer',
 'sarcomatoid mesothelioma': 'Thoracic Cancer',
 'kidney medullary carcinoma': 'Urinary System Cancer',
 'choriocarcinoma': 'Reproductive System Cancer',
 'krukenberg tumor': 'Reproductive System Cancer',
 'maxillary sinus squamous cell carcinoma': 'Head and Neck Cancer',
 'malignant peripheral nerve sheath tumor': 'Connective and Soft Tissue Cancer',
 'malignant mesothelioma': 'Unclassified',
 'alveolar ridge squamous cell carcinoma': 'Head and Neck Cancer',
 'splenic marginal zone lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'malignant mixed mesodermal (mullerian) tumor': 'Reproductive System Cancer',
 'cervical poorly differentiated adenosquamous carcinoma': 'Reproductive System Cancer',
 'floor of mouth squamous cell carcinoma': 'Head and Neck Cancer',
 'anal cancer': 'Digestive System Cancer',
 'bladder cancer': 'Urinary System Cancer',
 'cervix cancer': 'Reproductive System Cancer',
 'central nervous system cancer': 'Nervous System Cancer',
 'colon cancer': 'Digestive System Cancer',
 'gastric stromal cancer gist': 'Connective and Soft Tissue Cancer',
 'gastric cancer': 'Digestive System Cancer',
 'head and neck cancer': 'Head and Neck Cancer',
 'leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'liver cancer': 'Digestive System Cancer',
 'lung cancer': 'Thoracic Cancer',
 'nsclc': 'Thoracic Cancer',
 'small cell lung cancer': 'Endocrine Cancer',
 'breast cancer': 'Breast Cancer',
 'oesophagus cancer': 'Digestive System Cancer',
 'ovarian cancer': 'Reproductive System Cancer',
 'pancreatic cancer': 'Digestive System Cancer',
 'prostate cancer': 'Reproductive System Cancer',
 'pleuramesothelioma': 'Thoracic Cancer',
 'renal cancer': 'Urinary System Cancer',
 'epidermal carcinoma': 'Skin Cancer',
 'sarcoma': 'Connective and Soft Tissue Cancer',
 'soft tissue sarcoma': 'Connective and Soft Tissue Cancer',
 'thyroid cancer': 'Head and Neck Cancer',
 'testis cancer': 'Reproductive System Cancer',
 'uterus cancer': 'Reproductive System Cancer',
 'unknown cancer': 'Not provided',
 'cervix cancer, caucasian': 'Reproductive System Cancer',
 'colon cancer (asian)': 'Digestive System Cancer',
 'colon cancer (caucasian, europe)': 'Digestive System Cancer',
 'gastric cancer (caucasian)': 'Digestive System Cancer',
 'leukemia (aml)': 'Hematopoietic and Lymphoid System Cancer',
 'liver cancer (caucasian, cholangiocarcinoma)': 'Digestive System Cancer',
 'nsclc (caucasian, adenocarcinoma subtype)': 'Thoracic Cancer',
 'nsclc (caucasian, epidermoid subtype)': 'Thoracic Cancer',
 'lymphoma (dlbcl)': 'Hematopoietic and Lymphoid System Cancer',
 'breast cancer (her2-enriched)': 'Breast Cancer',
 'breast cancer (triple negative)': 'Breast Cancer',
 'pancreatic cancer (caucasian)': 'Digestive System Cancer',
 'renal cancer (caucasian)': 'Urinary System Cancer',
 'lung cancer acinar adenocarcinoma': 'Thoracic Cancer',
 'pancreatic cancer squamous cell carcinoma': 'Digestive System Cancer',
 'breast cancer metaplastic ductal carcinoma': 'Breast Cancer',
 'ampulla of vater cancer adenocarcinoma': 'Digestive System Cancer',
 'colorectal cancer mucinous adenocarcinoma': 'Digestive System Cancer',
 'rare cancers adenocarcinoma': 'Digestive System Cancer',
 'other sessile serrated adenoma': 'Digestive System Cancer',
 'other tubulovillous adenoma': 'Digestive System Cancer',
 'intrahepatic bile duct cancer intrahepatic cholangiocarcinoma': 'Digestive System Cancer',
 'rare cancers extrahepatic cholangiocarcinoma': 'Digestive System Cancer',
 'colorectal cancer medullary carcinoma': 'Digestive System Cancer',
 'breast cancer infiltrating ductal carcinoma': 'Breast Cancer',
 'pancreatic cancer infiltrating ductal carcinoma': 'Digestive System Cancer',
 'rare cancers noninfiltrating intraductal papillary adenocarcinoma': 'Digestive System Cancer',
 'breast cancer pleomorphic carcinoma': 'Breast Cancer',
 'breast cancer other': 'Breast Cancer',
 'ampulla of vater cancer neuroendocrine carcinoma, large cell': 'Digestive System Cancer',
 'rare cancers atypical carcinoid tumor': 'Digestive System Cancer',
 'endometrial cancer serous carcinoma': 'Reproductive System Cancer',
 'rare cancers small intestine cancer': 'Digestive System Cancer',
 'head and neck cancer: lip and oral cavity squamous cell carcinoma, conventional': 'Head and Neck Cancer',
 'endometrial cancer carcinosarcoma (malignant mixed mullerian tumor)': 'Reproductive System Cancer',
 'pancreatic cancer invasive adenocarcinoma arising from ipmn': 'Digestive System Cancer',
 'colorectal cancer undifferentiated carcinoma': 'Digestive System Cancer',
 'pancreatic cancer noninfiltrating intraductal papillary adenocarcinoma': 'Digestive System Cancer',
 'pancreatic cancer intraductal papillary mucinous neoplasm (ipmn, main duct/mixed)': 'Digestive System Cancer',
 'colorectal cancer squamous cell carcinoma': 'Digestive System Cancer',
 'rare cancers carcinoma of unknown primary': 'Unclassified',
 'rare cancers squamous cell carcinoma': 'Skin Cancer',
 'lung cancer non-small cell carcinoma': 'Thoracic Cancer',
 'pancreatic cancer carcinosarcoma': 'Digestive System Cancer',
 'endometrial cancer endometrioid carcinoma, other variant': 'Reproductive System Cancer',
 'breast cancer lobular carcinoma': 'Breast Cancer',
 'colorectal cancer other': 'Digestive System Cancer',
 'ovarian cancer mucinous borderline tumor/atypical proliferative mucinous tumor': 'Reproductive System Cancer',
 'ovarian cancer clear cell carcinoma': 'Reproductive System Cancer',
 'head and neck cancer: larynx': 'Head and Neck Cancer',
 'ovarian cancer serous cystadenoma, borderline': 'Reproductive System Cancer',
 'hepatocellular carcinoma trabecular and micro-acinar cells variant': 'Digestive System Cancer',
 'pancreatic cancer neuroendocrine carcinoma': 'Digestive System Cancer',
 'rare cancers transitional cell carcinoma': 'Urinary System Cancer',
 'rare cancers mucinous adenocarcinoma': 'Digestive System Cancer',
 'ampulla of vater cancer tubulovillous adenoma': 'Digestive System Cancer',
 'head and neck cancer: pharynx squamous cell carcinoma': 'Head and Neck Cancer',
 'endometrial cancer endometrial carcinoma with serous component': 'Reproductive System Cancer',
 'head and neck cancer: paranasal sinuses and nasal cavity squamous cell carcinoma (nos)': 'Head and Neck Cancer',
 'endometrial cancer mixed cell carcinoma': 'Reproductive System Cancer',
 'bladder urothelial carcinoma': 'Urinary System Cancer',
 'upper tract urothelial carcinoma': 'Urinary System Cancer',
 'pulmonary adenocarcinoma': 'Thoracic Cancer',
 'squamous cell carcinomas': 'Thoracic Cancer',
 'large-cell carcinoma': 'Thoracic Cancer',
 'ovarian undifferentiated carcinoma': 'Reproductive System Cancer',
 'glioblastoma nos 4': 'Nervous System Cancer',
 'metastasis lung': 'Nervous System Cancer',
 'medulloblastoma 4': 'Nervous System Cancer',
 'anaplastic oligodendroglioma nos 3': 'Nervous System Cancer',
 'glioblastoma idh wildtype 4': 'Nervous System Cancer',
 'metastasis breast': 'Breast Cancer',
 'glioblastoma idh mutant 4': 'Nervous System Cancer',
 'metastasis melanoma': 'Skin Cancer',
 'pineoblastoma 4': 'Nervous System Cancer',
 'anaplastic astrocytoma nos': 'Nervous System Cancer',
 'acute b lymphoblastic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'pre-b all': 'Hematopoietic and Lymphoid System Cancer',
 'down syndrome acute lymphocytic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 't-cell acute lymphoblastic leukaemia': 'Hematopoietic and Lymphoid System Cancer',
 'metastasis esophagus': 'Digestive System Cancer',
 'lymphoma cns secondary': 'Hematopoietic and Lymphoid System Cancer',
 'metastasis colon': 'Digestive System Cancer',
 'high grade glioma iii': 'Nervous System Cancer',
 'metastasis ovary': 'Reproductive System Cancer',
 'high grade glioma nos': 'Nervous System Cancer',
 'metastasis yolk sac tumor': 'Unclassified',
 'atypical teratoid rhabdoid tumor 4': 'Nervous System Cancer',
 'metastasis prostate': 'Reproductive System Cancer',
 'metastasis sarcoma': 'Connective and Soft Tissue Cancer',
 'metastasis larynx': 'Head and Neck Cancer',
 'metastasis uterine': 'Reproductive System Cancer',
 'metastasis pancreas': 'Digestive System Cancer',
 'lymphoma cns': 'Hematopoietic and Lymphoid System Cancer',
 'b/myeloid all': 'Hematopoietic and Lymphoid System Cancer',
 'blastic plasmacytoid dendritic cell neoplasm': 'Hematopoietic and Lymphoid System Cancer',
 'juvenile myelomonocytic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'femaleollicular lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'double-hit non-hodgkin lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'non-hodgkin lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'burkitt lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'marginal zone lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'carcinoma': 'Reproductive System Cancer',
 'myelodysplastic syndromes': 'Hematopoietic and Lymphoid System Cancer',
 't-cell-prolymphocytic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'angioimmunoblastic t-cell lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'adult t-cell leukemia/lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 't lymphoblastic lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'peripheral t-cell lymphoma not other specified': 'Hematopoietic and Lymphoid System Cancer',
 'nk-t-cell lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'sezary': 'Hematopoietic and Lymphoid System Cancer',
 'chronic myelomonocytic leukaemia to acute myeloid leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'invasive adenocarcinoma': 'Thoracic Cancer',
 'adenocarcinoma': 'Reproductive System Cancer',
 'invasive ductal carcinoma': 'Breast Cancer',
 'sacromatoid carcinoma': 'Thoracic Cancer',
 'moderately to poorly differentiated, with mucinous differentiation, t2n0mx': 'Digestive System Cancer',
 'squamous cell carcinoma': 'Thoracic Cancer',
 'ductal carcinoma': 'Breast Cancer',
 'invasive carcinoma': 'Thoracic Cancer',
 'necrotic tumor and inflammatory cells': 'Urinary System Cancer',
 't3n1mx, triple neg': 'Breast Cancer',
 'metastatic adenocarcinoma': 'Thoracic Cancer',
 'non small cell carcinoma': 'Thoracic Cancer',
 'invasive mammary ductal carcinoma': 'Breast Cancer',
 'metastasis liver': 'Digestive System Cancer',
 'high grade serous carcinoma': 'Reproductive System Cancer',
 'adenosquamous carcinoma': 'Digestive System Cancer',
 'metaplastic carcinoma; triple neg': 'Breast Cancer',
 'endometriod adenocarcinoma': 'Unclassified',
 'carcinosarcoma': 'Reproductive System Cancer',
 'ductal adenocarcinoma': 'Breast Cancer',
 'serous carcinoma': 'Reproductive System Cancer',
 'not collected': 'Unclassified',
 'transitional cell carcinoma, t3bnxmx': 'Unclassified',
 'moderately differentiated mucinous carcinoma': 'Reproductive System Cancer',
 'high grade mixed epithelial type carcinoma, serous carcinoma and clear cell carcinoma, t1an0mx': 'Reproductive System Cancer',
 'malignant mixed mullerian tumor': 'Reproductive System Cancer',
 'carcinosarcoma/malignant mullerian mixed tumor': 'Reproductive System Cancer',
 'heptocellular carcinoma': 'Digestive System Cancer',
 'clear cell adenocarcinoma': 'Reproductive System Cancer',
 'yolk sac tumor': 'Reproductive System Cancer',
 'serous adenocarcinoma': 'Reproductive System Cancer',
 'metastasis intestine': 'Digestive System Cancer',
 'low grade urothelial (transitional cell) carcinoma; tan0mn/a': 'Urinary System Cancer',
 'high grade. carcinosarcoma, with mixed heterologous (rhabdomyosarcoma) and homologous (undifferentiated sarcoma) differentiation.': 'Reproductive System Cancer',
 'large neuroendocrine carcinoma; t2an0mn/a': 'Endocrine Cancer',
 'metastatic gastric neuroendocrine carcinoma': 'Digestive System Cancer',
 'mucinous adenocarcinoma of the colon, per path report': 'Digestive System Cancer',
 'alveolar soft part sarcoma': 'Connective and Soft Tissue Cancer',
 'cns embryonal nos': 'Nervous System Cancer',
 'extracranial rhabdoid': 'Unclassified',
 'fusion negative rhabdomyosarcoma': 'Connective and Soft Tissue Cancer',
 'wilms': 'Urinary System Cancer',
 'fusion positive rhabdomyosarcoma': 'Connective and Soft Tissue Cancer',
 'small cell carcinoma': 'Thoracic Cancer',
 'clear cell sarcoma': 'Connective and Soft Tissue Cancer',
 'adenocarcinoma, metastatic, nos': 'Breast Cancer',
 'infiltrating duct carcinoma, nos': 'Breast Cancer',
 'carcinoma, metastatic, nos': 'Unclassified',
 'adenoid cystic carcinoma': 'Breast Cancer',
 'intraductal carcinoma, noninfiltrating, nos': 'Breast Cancer',
 'metaplastic carcinoma, nos': 'Breast Cancer',
 'intraductal micropapillary carcinoma': 'Breast Cancer',
 'mixed multi-centric disease - idc and dcis': 'Breast Cancer',
 'invasive lobular carcinoma': 'Breast Cancer',
 'poorly differentiated carcinoma': 'Head and Neck Cancer',
 'ductal carcinoma in situ': 'Breast Cancer',
 'lpsilateral breast tumor recurrence': 'Not provided',
 'cystosarcoma phyllodes tumor': 'Breast Cancer',
 'dcis; idc': 'Breast Cancer',
 'metaplastic carcinoma': 'Breast Cancer',
 'intraductal carcinoma; noninfiltrating; nos': 'Breast Cancer',
 'infiltrating duct carcinoma; nos': 'Breast Cancer',
 'lobular carcinoma in situ; nos': 'Breast Cancer',
 'gastroesophageal junction adenocarcinoma': 'Digestive System Cancer',
 'lung squamous cell carcinoma': 'Thoracic Cancer',
 'acute monocytic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'endometrial cancer': 'Reproductive System Cancer',
 'cancer': 'Urinary System Cancer',
 'b-cell adult acute lymphocytic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'carcinoma: urothelial carcinoma': 'Urinary System Cancer',
 'papillary serous adenocarcinoma': 'Reproductive System Cancer',
 'brain glioblastoma multiforme': 'Nervous System Cancer',
 'acute leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'bladder urothelial papillary carcinoma': 'Urinary System Cancer',
 'mature t-cell and nk-cell lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'urinary bladder urothelial carcinoma': 'Urinary System Cancer',
 'urinary bladder cancer': 'Urinary System Cancer',
 'kidney rhabdoid cancer': 'Urinary System Cancer',
 'spindle cell sarcoma': 'Connective and Soft Tissue Cancer',
 'uterine cancer': 'Reproductive System Cancer',
 'luminal breast carcinoma': 'Breast Cancer',
 'lung small cell carcinoma': 'Endocrine Cancer',
 'rectum adenocarcinoma': 'Digestive System Cancer',
 'pleomorphic carcinoma': 'Thoracic Cancer',
 'acute lymphocytic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'pancreas adenocarcinoma': 'Digestive System Cancer',
 'pediatric osteosarcoma': 'Connective and Soft Tissue Cancer',
 'chronic myeloid leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'brain glioma': 'Nervous System Cancer',
 'lung mixed small cell and squamous cell carcinoma': 'Thoracic Cancer',
 'large cell neuroendocrine carcinoma': 'Endocrine Cancer',
 'mucoepidermoid carcinoma': 'Head and Neck Cancer',
 'transitional cell carcinoma': 'Urinary System Cancer',
 'mucinous adenocarcinoma': 'Digestive System Cancer',
 'leiomyosarcoma': 'Connective and Soft Tissue Cancer',
 'appendix carcinoma': 'Digestive System Cancer',
 'urothelial carcinoma': 'Urinary System Cancer',
 'adult t-cell leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'ovary serous adenocarcinoma': 'Reproductive System Cancer',
 't-cell adult acute lymphocytic leukemia': 'Hematopoietic and Lymphoid System Cancer',
 'breast metaplastic carcinoma': 'Breast Cancer',
 'neuroendocrine tumor': 'Endocrine Cancer',
 'b-cell lymphoma': 'Hematopoietic and Lymphoid System Cancer',
 'pediatric ependymoma': 'Nervous System Cancer',
 'ovarian serous carcinoma': 'Reproductive System Cancer',
 'ovary papillary carcinoma': 'Reproductive System Cancer',
 'rhabdoid cancer': 'Not provided',
 'tonsil cancer': 'Head and Neck Cancer',
 'invasvie ductal carcinoma': 'Breast Cancer',
 't2 transitional cell carcinoma': 'Urinary System Cancer',
 'breast lobular carcinoma': 'Breast Cancer',
 'gastrointestinal stromal tumor': 'Connective and Soft Tissue Cancer',
 'neuroendocrine carcinoma': 'Digestive System Cancer',
 'glioblastoma, idh-wildtype': 'Digestive System Cancer',
 'glioma, idh-mutant': 'Nervous System Cancer',
 'glioblastoma, idh-mutant': 'Nervous System Cancer',
 'embryonal tumors with multilayered rosettes': 'Nervous System Cancer',
 'ependymoma': 'Nervous System Cancer',
 'ependymoblastoma': 'Nervous System Cancer',
 'cns ewing sarcoma family tumor with cic alteration': 'Connective and Soft Tissue Cancer',
 'cns germinoma': 'Nervous System Cancer',
 'metaplastic spindle': 'Breast Cancer',
 'ductal': 'Breast Cancer',
 'metaplastic': 'Breast Cancer',
 'squamous cell': 'Thoracic Cancer',
 'cystic papillary carcinoma': 'Unclassified',
 'adenosquamous': 'Thoracic Cancer',
 'other neoplasm': 'Thoracic Cancer',
 'large cell': 'Thoracic Cancer',
 'carcinoid': 'Endocrine Cancer',
 'nsclc (nos)': 'Thoracic Cancer',
 'squamous': 'Thoracic Cancer',
 'atypical adenorcarcinoma': 'Thoracic Cancer',
 'adenocarcinoma (60% acinar and 30% micropapillary and 10% sarcomatoid)': 'Thoracic Cancer',
 'adenocarcinomain': 'Unclassified',
 'sq': 'Thoracic Cancer',
 'poorly differentiated squamous carcinoma with focal glandular formation of poorly differentiated adenocarcinoma': 'Thoracic Cancer',
 'well differentiated adenocarcinoma': 'Thoracic Cancer',
 'bac': 'Thoracic Cancer',
 'ad and sc carcinoma': 'Thoracic Cancer',
 'ad and bac': 'Unclassified',
 'ad': 'Thoracic Cancer',
 'mesothelioma epithelial type': 'Unclassified',
 'pleomorphic carcinoma (15%) with poorly differentiated squamous carcinoma (85%)': 'Thoracic Cancer',
 'moderate to poorly differentiated squamous cell carcinoma (3.0 cm in maximal  dimension)': 'Thoracic Cancer',
 'invasive moderately differentiated lung adenocarcinoma; papillary predominant  (60% papillary and 40% acinar subtypes);': 'Thoracic Cancer',
 'adenocarcinoma 90% solid with 10% acinar subtype': 'Thoracic Cancer',
 'invasive ductal carcinoma, not otherwise specified': 'Breast Cancer',
 'adenocarcinoma - colon': 'Digestive System Cancer',
 'invasive breast carcinoma': 'Breast Cancer',
 'cholangiocar.- intra/extrahepatic': 'Digestive System Cancer',
 'ovarian cancer, nos': 'Reproductive System Cancer',
 'serous endometrial adenocarcinoma': 'Reproductive System Cancer',
 'adenocarcinoma - pancreas': 'Digestive System Cancer',
 'penile squamous car.(epidermoid)': 'Reproductive System Cancer',
 'urothelial/bladder cancer, nos': 'Urinary System Cancer',
 'pharyngeal squam. cell carcinoma': 'Head and Neck Cancer',
 'adenocarcinoma - rectum': 'Digestive System Cancer',
 'inflammatory breast carcinoma': 'Breast Cancer',
 'rcc, clear cell adenocarcinoma': 'Urinary System Cancer',
 'salivary gland cancer': 'Head and Neck Cancer',
 'ovarian epithelial cancer': 'Reproductive System Cancer',
 'soft tissue neoplasm, nos': 'Connective and Soft Tissue Cancer',
 'malig. periph. nerve sheath tum.': 'Connective and Soft Tissue Cancer',
 'squamous cervical cancer': 'Reproductive System Cancer',
 'endometrioid endomet. adenocar.': 'Reproductive System Cancer',
 'non-rhabdo. soft tissue sarcoma': 'Connective and Soft Tissue Cancer',
 'transitional cell car. - uroth.': 'Urinary System Cancer',
 'malignant fibrous histiocytoma': 'Connective and Soft Tissue Cancer',
 'glioblastoma multiforme': 'Nervous System Cancer',
 'adenocarcinoma, nos': 'Unclassified',
 'neuroendocrine cancer, nos': 'Endocrine Cancer',
 'carcinosarcoma of the uterus': 'Reproductive System Cancer',
 'adenocarcinoma - small intest.': 'Digestive System Cancer',
 'squamous cell carcinoma - skin': 'Skin Cancer',
 'leiomyosarcoma - uterus': 'Connective and Soft Tissue Cancer',
 'small cell car. (extrapulmonary)': 'Endocrine Cancer',
 'fibrosarcoma - not infantile': 'Connective and Soft Tissue Cancer',
 'h & n squamous cell car., nos': 'Head and Neck Cancer',
 'adenocarcinoma - stomach': 'Digestive System Cancer',
 'female reprod. system cancer, nos': 'Reproductive System Cancer',
 'lip/oral cavity squam. cell car.': 'Head and Neck Cancer',
 'non-small cell lung cancer, nos': 'Thoracic Cancer',
 'ewing sarcoma/peripheral pnet': 'Connective and Soft Tissue Cancer',
 'hurthle cell neoplasm (thyroid)': 'Endocrine Cancer',
 'colorectal cancer, nos': 'Digestive System Cancer',
 'squamous cell carcinoma - anus': 'Digestive System Cancer',
 'leiomyosarcoma - not uterine': 'Connective and Soft Tissue Cancer',
 'vaginal cancer, nos': 'Reproductive System Cancer',
 'rhabdomyosarcoma, nos': 'Connective and Soft Tissue Cancer',
 'adenocarcinoma - esophagus': 'Digestive System Cancer',
 'gastrointestinal cancer, nos': 'Digestive System Cancer',
 'prostate cancer, nos': 'Reproductive System Cancer',
 'adrenocortical carcinoma': 'Endocrine Cancer',
 'uterine cancer, nos': 'Reproductive System Cancer',
 'vulvar cancer, nos': 'Reproductive System Cancer',
 'cervical cancer, nos': 'Reproductive System Cancer',
 'mesothelioma': 'Unclassified',
 'miscellaneous neoplasm, nos': 'Unclassified',
 'gastric cancer, nos': 'Digestive System Cancer',
 'renal cell carcinoma, nos': 'Urinary System Cancer',
 'adenocarcinoma - cervix': 'Reproductive System Cancer',
 'pancreatic cancer (not islets)': 'Digestive System Cancer',
 'nhl, nos': 'Hematopoietic and Lymphoid System Cancer',
 'merkel cell tumor': 'Endocrine Cancer',
 'squamous cell car. - esophagus': 'Digestive System Cancer',
 'islet cell tumors - pancreas': 'Digestive System Cancer',
 'primary peritoneal carcinoma': 'Peritoneal and Retroperitoneal Cancer',
 'lung cancer, nos': 'Thoracic Cancer',
 'liver/hepatobiliary cancer': 'Digestive System Cancer',
 'breast cancer, nos': 'Breast Cancer',
 'basal cell carcinoma': 'Skin Cancer',
 'mullerian mixed tumour': 'Reproductive System Cancer',
 'endometrioid adenocarcinoma': 'Unclassified',
 'ampullary adenocarcinoma': 'Digestive System Cancer',
 'mucinous cystadenocarcinoma': 'Unclassified',
 'ipmn, invasive mucinous noncystic adenocarcinoma': 'Digestive System Cancer',
 'undifferentiated carcinoma': 'Digestive System Cancer',
 'mucinous noncystic adenocarcinoma': 'Digestive System Cancer',
 'ipmn, non invasive': 'Digestive System Cancer',
 'acinar cell carcinoma': 'Digestive System Cancer',
 'lung large cell ': 'Not provided',
 'lung large cell neuroendocrine carcinoma': 'Endocrine Cancer',
 'lung adenocarcinoma + neuroendocrine differentiation': 'Thoracic Cancer',
 'lung adenocarcinoma ': 'Not provided',
 'combined small cell lung cancer and large cell neuroendocrine carcinoma and adenocarcinoma': 'Thoracic Cancer',
 'lung pleomorphic carcinoma (with squamous cell component)': 'Thoracic Cancer',
 'lung adenocarcinoma, mucinous': 'Thoracic Cancer',
 'lung pleomorphic carcinoma (with adenocarcinoma component)': 'Thoracic Cancer',
 'lung squamous cell carcinoma ': 'Not provided',
 'lung squamous cell carcinoma, basaloid': 'Thoracic Cancer',
 'lung squamous cell carcinoma (sqcc)': 'Thoracic Cancer',
 'lung combined adenocarcinoma (90%) and large cell neuroendocrine carcinoma (10%)': 'Thoracic Cancer',
 'lung squamous cell carcinoma, basaloid ': 'Not provided',
 'lung adenosquamous carcinoma ': 'Not provided',
 'breast invasive ductal carcinoma': 'Breast Cancer',
 'lung squamous carcinoma': 'Thoracic Cancer',
 'lung typical carcinoid': 'Endocrine Cancer',
 'undifferentiated lung carcinoma with a large cell neuroendocrine carcinoma': 'Endocrine Cancer',
 'other tubular adenoma': 'Digestive System Cancer',
 'colorectal cancer adenocarcinoma, intestinal type': 'Digestive System Cancer',
 'adrenal cortical carcinoma': 'Endocrine Cancer',
 'desmoplastic small round cell tumor': 'Connective and Soft Tissue Cancer',
 'gist': 'Connective and Soft Tissue Cancer',
 'high grade sarcoma': 'Connective and Soft Tissue Cancer',
 'fibromyxoid sarcoma': 'Connective and Soft Tissue Cancer',
 'rhabdoid tumor of kidney': 'Unclassified',
 'parathyroid carcinoma': 'Endocrine Cancer',
 'undifferentiated round cell sarcoma': 'Connective and Soft Tissue Cancer',
 'embroyonal sarcoma': 'Connective and Soft Tissue Cancer',
 'wilms tumor': 'Unclassified',
 'adrenal cortical carcinoma ': 'Not provided',
 'germ cell tumor': 'Reproductive System Cancer',
 'moderately diffentiated pancreatic ductal adenocarcinoma': 'Digestive System Cancer',
 'moderately to poorly differentiated pancreatic ductal adenocarcinoma': 'Digestive System Cancer',
 'poorly differentiated pancreatic ductal adenocarcinoma': 'Digestive System Cancer',
 'poorly diffentiated pancreatic ductal adenocarcinoma': 'Digestive System Cancer',
 'pancreatic acinar cell carcinoma with neuroendocrine differentiation': 'Digestive System Cancer',
 'uterine corpus myxoid leiomyosarcoma': 'Connective and Soft Tissue Cancer',
 'cutaneous malignant melanoma': 'Skin Cancer',
 'cutaneous superficial spreading malignant melanoma': 'Skin Cancer',
 'cutaneous nodular malignant melanoma': 'Skin Cancer',
 'high grade serous ovarian cancer': 'Reproductive System Cancer',
 'carcinosarcoma ovarian cancer': 'Reproductive System Cancer',
 'low grade serous ovarian cancer': 'Reproductive System Cancer',
 'endometrioid ovarian cancer': 'Reproductive System Cancer',
 'metastatic breast carcinoma': 'Breast Cancer',
 'intraductal breast neoplasm': 'Breast Cancer',
 'rectal adenocarcinoma ': 'Not provided',
 'colon adenocarcinoma ': 'Breast Cancer',
 'colorectal cancer': 'Digestive System Cancer',
 'rectal mucinous adenocarcinoma ': 'Not provided',
 'rectal cribriform comedo-type adenocarcinoma': 'Digestive System Cancer',
 'cecum  adenocarcinoma': 'Digestive System Cancer',
 'pancreatic carcinoma - infiltrating ductal adenocarcinoma (idac)': 'Digestive System Cancer',
 'pancreatic carcinoma - infiltrating ductal adenocarcinoma (idac) + intraductal papillary mucinous neoplasm (ipmn)': 'Digestive System Cancer',
 'pancreatic carcinoma - intraductal papillary mucinous neoplasm with nvasive carcinoma': 'Digestive System Cancer',
 'ovarian cancer mucinous carcinoma': 'Reproductive System Cancer',
 'lung cancer invasive mucinous adenocarcinoma with signet ring features': 'Thoracic Cancer',
 'lung cancer invasive adenocarcinoma, acinar predominant': 'Thoracic Cancer',
 'endometrial cancer endometrioid carcinoma with secretory differentiation': 'Reproductive System Cancer',
 'endometrial cancer endometrioid carcinoma with squamous differentiation': 'Reproductive System Cancer',
 'rare cancers papillary transitional cell carcinoma': 'Unclassified',
 'endometrial cancer endometrioid carcinoma, nos': 'Reproductive System Cancer',
 'rare cancers adenocarcinoma, intestinal type': 'Urinary System Cancer',
 'stomach cancer invasive adenocarcinoma with conventional and enteroblastic differentiation': 'Digestive System Cancer',
 'pancreatic neuroendocrine carcinoma': 'Digestive System Cancer',
 'sarcoma synovial sarcoma': 'Connective and Soft Tissue Cancer',
 'sarcoma braf mutated gist': 'Connective and Soft Tissue Cancer',
 'sarcoma gist': 'Connective and Soft Tissue Cancer',
 'sarcoma leiomyosarcoma': 'Connective and Soft Tissue Cancer',
 'sarcoma metastatic sarcoma; unknown subtype': 'Connective and Soft Tissue Cancer',
 'sarcoma radiation therapy induced osteosarcoma; 2nd isolation from same patient as shim1': 'Connective and Soft Tissue Cancer',
 'sarcoma sarcoma from lung met; unknown subtype': 'Connective and Soft Tissue Cancer',
 'basal': 'Breast Cancer',
 'her2-e': 'Breast Cancer',
 'claudin-low': 'Breast Cancer',
 'lumb': 'Breast Cancer',
 'non-acral cutaneous melanoma': 'Skin Cancer',
 'nodular; ns; mis; ssm melanoma': 'Skin Cancer',
 'nodular melanoma': 'Skin Cancer',
 'mis melanoma': 'Skin Cancer',
 'ssm melanoma': 'Skin Cancer',
 'ssm; ns; lm melanoma': 'Skin Cancer',
 'ns melanoma': 'Unclassified',
 'mucosal melanoma': 'Unclassified',
 'non-acral melanoma': 'Skin Cancer',
 'ns; mis; ssm melanoma': 'Not provided',
 'non-acral cutaneousmelanoma': 'Skin Cancer',
 'nodular; non-acral cutaneous melanoma': 'Skin Cancer',
 'acral melanoma': 'Skin Cancer',
 'lmm melanoma': 'Skin Cancer',
 'nodular; ssm melanoma': 'Skin Cancer',
 'acral cutaneous melanoma': 'Skin Cancer'}