import pandas as pd
from pandas import read_csv



input_file = {
    #'latest': 'https://www.cancermodels.org/api/model_molecular_metadata?select=sample_id,data_source,data_type,platform_name,model_id',
    'DR_6.2': 'assets/sample/DR_v6.2.csv', 'DR_6.1': 'assets/sample/DR_v6.1.csv', 'DR_6.0': 'assets/sample/DR_v6.0.csv',
    'DR_5.3': 'assets/sample/DR_v5.3.csv', 'DR_5.2': 'assets/sample/DR_v5.2.csv', 'DR_5.1': 'assets/sample/DR_v5.1.csv',
              'DR_4.0': 'assets/sample/DR_v4.0.csv',
              'DR_3.0': 'assets/sample/DR_v3.0.csv',
              'DR_2.1': 'assets/sample/DR_v2.1.csv', 'DR_2.0': 'assets/sample/DR_v2.0.csv',
              'DR_1.0': 'assets/sample/DR_v1.0.csv'}

labels = {'DR_6.2': 'Data release 6.2', 'DR_6.1': 'Data release 6.1', 'DR_6.0': 'Data release 6.0',
    #'latest': 'Latest Release',
          'DR_5.3': 'Data release 5.3', 'DR_5.2': 'Data release 5.2', 'DR_5.1': 'Data release 5.1',
          'DR_4.0': 'Data release 4.0',
          'DR_3.0': 'Data release 3.0',
          'DR_2.1': 'Data release 2.1', 'DR_2.0': 'Data release 2.0',
          'DR_1.0': 'Data release 1.0'}

total_models = {
    'DR_6.2': 'assets/model/total_models_DR_v6.1.csv', 'DR_6.1': 'assets/model/total_models_DR_v6.1.csv', 'DR_6.0': 'assets/model/total_models_DR_v6.0.csv',
    #'latest': 'https://www.cancermodels.org/api/model_metadata?select=model_id,data_source,type,pubmed_ids,patient_age,histology,tumor_type,primary_site,patient_sex,patient_ethnicity',
                'DR_5.3': 'assets/model/total_models_DR_v5.3.csv', 'DR_5.2': 'assets/model/total_models_DR_v5.2.csv', 'DR_5.1': 'assets/model/total_models_DR_v5.1.csv',
              'DR_4.0': 'assets/model/total_models_DR_v4.0.csv',
              'DR_3.0': 'assets/model/total_models_DR_v3.0.csv',
              'DR_2.1': 'assets/model/total_models_DR_v2.1.csv', 'DR_2.0': 'assets/model/total_models_DR_v2.0.csv',
              'DR_1.0': 'assets/model/total_models_DR_v1.0.csv'}

reactive_categories = {'Providers': 'provider', 'Model Type': 'model_type',
                 'Publications': 'publications', 'Age': 'age_in_years_at_collection',
                 'Diagnosis': 'diagnosis', 'Tumour Type': 'tumour_type',
                 'Primary Site': 'primary_site', 'Gender': 'sex', 'Ethnicity': 'ethnicity'}

primary_site_mapping = {
    'Brain': 'Central Nervous System',
    'Brain Stem': 'Central Nervous System',
    'Cerebellum': 'Central Nervous System',
    'Cerebrum': 'Central Nervous System',
    'Spine': 'Central Nervous System',
    'Head': 'Head and Neck',
    'Head And Neck': 'Head and Neck',
    'Head Face Or Neck': 'Head and Neck',
    'Neck': 'Head and Neck',
    'Abdomen': 'Abdominal Cavity',
    'Abdominal Mass': 'Abdominal Cavity',
    'Abdominal Wall': 'Abdominal Cavity',
    'Abdominopelvic Cavity': 'Abdominal Cavity',
    'Digestive/Gastrointestinal': 'Gastrointestinal Tract',
    'Duodenum': 'Gastrointestinal Tract',
    'Colon': 'Gastrointestinal Tract',
    'Colon Cancer (Asian)': 'Gastrointestinal Tract',
    'Colon Cancer (Caucasian, Europe)': 'Gastrointestinal Tract',
    'Colorectal': 'Gastrointestinal Tract',
    'Connective Tissue': 'Soft Tissue',
    'Connective, Subcutaneous And Other Soft Tissues': 'Soft Tissue',
    'Esophagus': 'Gastrointestinal Tract',
    'Stomach': 'Gastrointestinal Tract',
    'Gastric': 'Gastrointestinal Tract',
    'Gastric Antrum': 'Gastrointestinal Tract',
    'Gastric Body Mucosa': 'Gastrointestinal Tract',
    'Gastric Cancer (Caucasian)': 'Gastrointestinal Tract',
    'Gastric Cardia': 'Gastrointestinal Tract',
    'Gastric Fundus': 'Gastrointestinal Tract',
    'Gastro Oesophageal Junction': 'Gastrointestinal Tract',
    'Gastroesophageal Junction': 'Gastrointestinal Tract',
    'Gastroesophageal Junction ': 'Gastrointestinal Tract',
    'Liver': 'Liver/Biliary System',
    'Liver And Intrahepatic Duct': 'Liver/Biliary System',
    'Liver Cancer (Caucasian, Cholangiocarcinoma)': 'Liver/Biliary System',
    'Hepatic Flexure': 'Gastrointestinal Tract',
    'Hepatic Flexure Of Colon': 'Gastrointestinal Tract',
    'Pancreas': 'Pancreas',
    'Pancreas Head': 'Pancreas',
    'Prostate Gland': 'Genitourinary System',
    'Renal Cancer (Caucasian)': 'Genitourinary System',
    'Kidney': 'Genitourinary System',
    'Testis': 'Genitourinary System',
    'Uterus': 'Genitourinary System',
    'Cervix': 'Genitourinary System',
    'Ovary': 'Genitourinary System',
    'Bladder': 'Genitourinary System',
    'Pelvis': 'Genitourinary System',
    'Lung': 'Respiratory System',
    'Lung Metastasis': 'Respiratory System',
    'Lung Recurrence  (What Does This Mean)': 'Respiratory System',
    'Lung Recurrence (Same)': 'Respiratory System',
    'Bronchus And Lung': 'Respiratory System',
    'Nsclc (Caucasian, Adenocarcinoma Subtype)': 'Respiratory System',
    'Nsclc (Caucasian, Epidermoid Subtype)': 'Respiratory System',
    'Esophagus At Gastro Oesophageal Junction': 'Gastrointestinal Tract',
    'Stomach ': 'Gastrointestinal Tract',  # Additional entry with extra space
    'Neck ': 'Head and Neck',  # Additional entry with extra space
}

diagnosis_to_cancer = read_csv('assets/diagnosis_mappings.tsv', sep='\t')
diagnosis_to_cancer = dict(zip(diagnosis_to_cancer['sample_diagnosis'], diagnosis_to_cancer['mappedTermLabel']))
#cancer_system = pd.read_json("https://www.cancermodels.org/api/model_metadata?select=histology,cancer_system").drop_duplicates()
#cancer_system['histology'] = cancer_system['histology'].str.title()
cancer_system = None

primary_site_mapping = {
    'Brain': 'Nervous System Cancer',
    'Breast': 'Breast Cancer',
    'Thyroid': 'Endocrine Cancer',
    'Haematopoietic and Lymphoid': 'Hematopoietic and Lymphoid System Cancer',
    'Cervix': 'Reproductive System Cancer',
    'Head and Neck': 'Head and Neck Cancer',
    'Central Nervous System': 'Nervous System Cancer',
    'Soft Tissue': 'Connective and Soft Tissue Cancer',
    'Ovary': 'Reproductive System Cancer',
    'unknown cancer': 'Unclassified',
    'Pancreas': 'Digestive System Cancer',
    'Frontal Cortex': 'Nervous System Cancer',
    'Parietal Lobe': 'Nervous System Cancer',
    'Thalamus': 'Nervous System Cancer',
    'Temporal Cortex': 'Nervous System Cancer',
    'Spine': 'Nervous System Cancer',
    'Lymph node': 'Hematopoietic and Lymphoid System Cancer',
    'breast': 'Breast Cancer',
    'pancreas': 'Digestive System Cancer',
    'Abdominal Mass': 'Unclassified',
    'Paracaval lymph Node': 'Unclassified',
    'Not provided': 'Unclassified',
    'Soft tissue': 'Connective and Soft Tissue Cancer',
    'Uterus': 'Reproductive System Cancer',
    'brain': 'Nervous System Cancer',
    'Brain stem': 'Nervous System Cancer',
    'Cerebrum': 'Nervous System Cancer',
    'Cerebellum': 'Nervous System Cancer',
    'Lung': 'Thoracic Cancer',
    'Gynecologic': 'Reproductive System Cancer',
    'Endocrine and Neuroendocrine': 'Endocrine Cancer',
    'lung': 'Thoracic Cancer',
    'Tibia': 'Connective and Soft Tissue Cancer',
    'Lung ': 'Thoracic Cancer',
    'Chest wall': 'Connective and Soft Tissue Cancer',
    'Axilla': 'Connective and Soft Tissue Cancer',
    'Femur ': 'Connective and Soft Tissue Cancer',
    'Chest wall ': 'Connective and Soft Tissue Cancer',
    'Retroperitoneum ': 'Connective and Soft Tissue Cancer',
    'Adrenal mass': 'Endocrine Cancer',
    'Distal pancreas/spleen': 'Digestive System Cancer',
    'Liver ': 'Digestive System Cancer',
    'Rectum': 'Digestive System Cancer',
    'colon': 'Digestive System Cancer',
    'Colon': 'Digestive System Cancer',
    'Right Colon': 'Digestive System Cancer',
    'Sigmoid Flexure': 'Digestive System Cancer',
    'Left colon': 'Digestive System Cancer',
    'ileocecal valve': 'Digestive System Cancer',
}
